/* header auto-generated by pidl */

#ifndef _PIDL_HEADER_ISDKey
#define _PIDL_HEADER_ISDKey

#include <util/data_blob.h>
#include <stdint.h>

#include <core/ntstatus.h>

#include <gen_ndr/misc.h>
#include <gen_ndr/security.h>
#ifndef _HEADER_ISDKey
#define _HEADER_ISDKey


struct GetKey {
	struct {
		uint32_t cbTargetSD;
		uint8_t *pbTargetSD;/* [ref,size_is(cbTargetSD)] */
		struct GUID *pRootKeyID;/* [unique] */
		int32_t L0KeyID;
		int32_t L1KeyID;
		int32_t L2KeyID;
	} in;

	struct {
		uint32_t *pcbOut;/* [ref] */
		uint8_t **ppbOut;/* [ref,size_is(,*pcbOut)] */
		HRESULT result;
	} out;

};

#endif /* _HEADER_ISDKey */
#endif /* _PIDL_HEADER_ISDKey */
